version: '3.7'

services:
    app:
        container_name: stats-angular
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf    
        ports:
            - "4201:8088"

volumes:
    content:
          

         
